const UserException = message => ({
  message,
  name: 'Error',
});

export default UserException;
